# Site settings
title: Reevoo Engineering
email: @reevoo.com
description: "Reevoo Engineering blog, documentation and open sourced projects."
baseurl: ""
url: "http://reevoo.com"
twitter_username: DevsAtReevoo
github_username:  reevoo

# Build settings
markdown: kramdown
permalink: pretty
