# Site settings
title: Reevoo Engineering
email: engineer@reevoo.com
description: "Reevoo Engineering blog, documentation and open sourced projects."
baseurl: ""
url: "http://reevoo.github.io"
twitter_username: DevsAtReevoo
github_username:  reevoo

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
